### ISSUE TITLE
How to add a project to the index?

### ISSUE THREAD

**Issue by gajus** [js-org/stats.js.org#6]
e.g. https://github.com/gajus/babel-plugin-react-css-modules This got 150 stars in the last 24 houts, but it does not appear in the index.

Two more projects got +100 stars in the last week but do not appear in the index.

**Comment by indus** [comment]
There is no way to manually add a repo. They get picked up by a bot when they have enough stars **and** forks.
So the number of forks counts as well; not only that - a fork counts roughly twice as much as a star (to respect the greater involvement). 
To be at 9999 you need about 220 stars  and zero forks or zero stars and about 110 stars; or any other combination that results in 17 "points".

**Comment by gajus** [comment]
> To be at 9999 you need about 220 stars and zero forks or zero stars and about 110 stars; or any other combination that results in 17 "points".

Did you mean:

> zero stars and about 110 forks

?

**Comment by indus** [comment]
Uhm - jep. Sorry!

**Comment by gajus** [comment]
> To be at 9999 you need about 220 stars and zero forks or zero stars and about 110 stars; or any other combination that results in 17 "points".

Now the project is 228 stars + 6 forks.

Regardless, it is not visible in the index.

**Comment by indus** [comment]
Found your Project: number 9775
Having problems with the bot lately, due to an switch to cloud-computing: https://github.com/js-org/stats.js.org/commits/master/_data/recs.csv (it sometimes idels and misses jobs)
